import React from 'react'

const page = () => {
  return (
    <div className='w-full'>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, laboriosam velit temporibus nam provident itaque molestiae doloremque sequi voluptatibus natus dolorem quod ut animi. Mollitia optio omnis exercitationem eligendi, accusantium voluptatem ab excepturi quaerat dolor sed reiciendis autem culpa recusandae libero voluptas molestiae maiores nemo nulla at, eaque iure odit laudantium. Eveniet doloribus ipsam beatae culpa eum optio reiciendis voluptatum ducimus esse illo totam maxime repellat, earum asperiores obcaecati, fugiat, voluptate maiores nesciunt cum distinctio. Accusamus reiciendis magni ratione error nam sapiente cum quia quam eius quis amet doloremque velit id, optio nobis. Architecto ratione praesentium corporis amet temporibus earum velit repellendus culpa dolorum vero nam exercitationem repudiandae iusto, alias quis cupiditate, assumenda laudantium, quae fugiat reprehenderit est sequi? Et pariatur dolores porro perferendis accusamus ullam eveniet recusandae odio explicabo autem numquam, perspiciatis eos. Ducimus quod rerum laboriosam fugit dolore quis nulla? Velit, iure labore? Omnis assumenda expedita harum delectus perferendis totam, soluta, quis quibusdam maxime repudiandae magnam odit sit corrupti molestias nam possimus et quae deserunt provident. Laudantium quaerat dignissimos, blanditiis atque voluptas, assumenda non minus facilis tempore, aspernatur dolorem. Repellendus laboriosam dolorum veniam sequi. Nesciunt veniam deserunt illo at harum corrupti, hic iusto nobis ea placeat delectus voluptates dolores sit recusandae dolorum, consequatur provident labore ratione ab officiis magnam qui obcaecati? Consequuntur maiores ducimus iusto quibusdam ipsa officia rem voluptate aperiam, sint quae sit aliquam eligendi aliquid doloremque vero dolorem. Ex sed, eos amet nihil nisi fugit aspernatur at debitis voluptas aliquam omnis quae illo alias reiciendis asperiores officiis ea sint cumque distinctio, voluptatem maxime sit officia! Asperiores ipsa iusto voluptatum, laborum autem architecto quam consequatur dolor, beatae distinctio maxime ut corporis minima accusamus omnis dicta ratione ullam ipsam similique modi obcaecati harum consequuntur dolore culpa. Quo recusandae vero distinctio perferendis dolorem facilis tempora dolorum eius rem deserunt!
    </div>
  )
}

export default page